import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Volume2, Mic, Copy, Trash2, ArrowRight, Share2, Download, 
  HelpCircle, Check, Sparkles, Languages, AlertCircle 
} from 'lucide-react';
import api from '../api';
import { FloatingElements } from '../components/FloatingElements';

export const TranslatorPage = () => {
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [translationResult, setTranslationResult] = useState(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [speechActive, setSpeechActive] = useState(false);

  const handleTranslate = async () => {
    if (!inputText.trim()) return;
    setLoading(true);
    setError('');
    
    try {
      const response = await api.post('/api/translate', { text: inputText });
      setTranslationResult(response.data);
    } catch (err) {
      console.error(err);
      setError('Translation failed. Please ensure the backend server is running.');
    } finally {
      setLoading(false);
    }
  };

  const handleClear = () => {
    setInputText('');
    setTranslationResult(null);
    setError('');
  };

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = () => {
    if (!translationResult) return;
    const shareUrl = `${window.location.origin}/share/${translationResult.id || 'temp'}`;
    navigator.clipboard.writeText(shareUrl);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  // Web Speech API text-to-speech
  const handleTextToSpeech = () => {
    if (!translationResult || !translationResult.translation) return;
    
    if ('speechSynthesis' in window) {
      // Cancel active
      window.speechSynthesis.cancel();
      
      const utterance = new SpeechSynthesisUtterance(translationResult.translation);
      utterance.lang = 'en-US';
      
      utterance.onstart = () => setSpeechActive(true);
      utterance.onend = () => setSpeechActive(false);
      utterance.onerror = () => setSpeechActive(false);
      
      window.speechSynthesis.speak(utterance);
    } else {
      alert("Text-to-speech is not supported in this browser.");
    }
  };

  // Mock Speech-to-text voice input
  const handleVoiceInput = () => {
    setIsRecording(true);
    // Simulate recording for 2.5 seconds
    setTimeout(() => {
      setIsRecording(false);
      const voiceOptions = [
        "Bhai order kab tak aayega?",
        "Lay bhari kaam kela tumhi!",
        "Aaj khub lyadh lagche, kichu korbo na.",
        "Sema kola mass performance pa!"
      ];
      setInputText(voiceOptions[Math.floor(Math.random() * voiceOptions.length)]);
    }, 2500);
  };

  // Download utilities (PDF and CSV format)
  const handleDownloadFile = (type) => {
    if (!translationResult) return;
    
    let content = "";
    let filename = "";
    let mimeType = "";

    if (type === 'csv') {
      content = "Input Slang,Translation,Language,Tone,Intent,Confidence\n";
      content += `"${inputText.replace(/"/g, '""')}","${translationResult.translation.replace(/"/g, '""')}","${translationResult.language}","${translationResult.tone}","${translationResult.intent}",${translationResult.confidence}\n`;
      filename = "bhasha_bridge_translation.csv";
      mimeType = "text/csv;charset=utf-8;";
    } else {
      // PDF Mock format text file
      content = "=========================================\n";
      content = "          BHASHA BRIDGE AI REPORT         \n";
      content += "=========================================\n\n";
      content += `Timestamp: ${new Date().toLocaleString()}\n`;
      content += `Source Language: ${translationResult.language}\n`;
      content += `Confidence Score: ${(translationResult.confidence * 100).toFixed(1)}%\n`;
      content += `Detected Tone: ${translationResult.tone}\n`;
      content += `Detected Intent: ${translationResult.intent}\n\n`;
      content += "-----------------------------------------\n";
      content += "INPUT SLANG TEXT:\n";
      content += `"${inputText}"\n\n`;
      content += "PROFESSIONAL ENGLISH TRANSLATION:\n";
      content += `"${translationResult.translation}"\n`;
      content += "-----------------------------------------\n\n";
      content += "SUGGESTED REPLIES:\n";
      translationResult.replies.forEach((r, i) => {
        content += `${i + 1}. "${r}"\n`;
      });
      content += "\nGenerated by Bhasha Bridge AI Translator.";
      filename = "bhasha_bridge_report.pdf";
      mimeType = "text/plain;charset=utf-8;";
    }

    const blob = new Blob([content], { type: mimeType });
    const link = document.createElement("a");
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute("href", url);
      link.setAttribute("download", filename);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  return (
    <div className="relative min-h-[calc(100vh-80px)] py-12 px-4 sm:px-6 lg:px-8 bg-slate-50 dark:bg-[#0b0f19] overflow-hidden">
      <FloatingElements />

      <div className="max-w-6xl mx-auto relative z-10 space-y-8">
        
        {/* Title */}
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <h1 className="text-3xl sm:text-4xl font-display font-bold text-gradient-dark">
            AI Slang Translator Playground
          </h1>
          <p className="text-sm sm:text-base text-slate-500 dark:text-slate-400">
            Input Indian internet slang and instantly get normalized, formal boardroom translations with intent markers.
          </p>
        </div>

        {error && (
          <div className="max-w-2xl mx-auto p-4 rounded-xl bg-red-50 dark:bg-red-950/20 border border-red-200/50 dark:border-red-900/50 text-red-600 dark:text-red-400 text-sm flex items-start space-x-2">
            <AlertCircle className="w-5 h-5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {/* Translation Columns */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          
          {/* Left Input Card */}
          <div className="glass-card rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800/80 bg-white/40 dark:bg-[#0f1422]/60 flex flex-col h-[420px] justify-between shadow-xl">
            <div className="space-y-4">
              <div className="flex items-center justify-between text-xs font-semibold text-slate-400 uppercase tracking-wider">
                <span>Input Slang Phrase</span>
                <span className="font-mono">{inputText.length} / 500</span>
              </div>
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value.substring(0, 500))}
                placeholder="Enter slang (e.g., 'Bhai order kab tak aayega?' or 'Aaj khub lyadh lagche')"
                className="w-full h-56 resize-none border-0 bg-transparent text-slate-800 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-0 text-lg leading-relaxed"
              />
            </div>

            {/* Input Action Controls */}
            <div className="flex items-center justify-between border-t border-slate-100 dark:border-slate-800/60 pt-4">
              <div className="flex space-x-2">
                <button
                  onClick={handleClear}
                  disabled={!inputText}
                  className="p-3 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 hover:text-red-500 hover:border-red-200 dark:hover:text-red-400 disabled:opacity-30 disabled:hover:text-slate-500 transition-all"
                  title="Clear Input"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
                <button
                  onClick={handleVoiceInput}
                  className={`p-3 border rounded-xl transition-all ${
                    isRecording 
                      ? 'bg-red-500 border-red-500 text-white animate-pulse' 
                      : 'border-slate-200 dark:border-slate-800 text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500'
                  }`}
                  title="Voice Input (Speech-to-Text)"
                >
                  <Mic className="w-5 h-5" />
                </button>
              </div>

              <button
                onClick={handleTranslate}
                disabled={!inputText.trim() || loading || isRecording}
                className="px-6 py-3 bg-brand-500 hover:bg-brand-600 disabled:opacity-50 text-white rounded-xl font-bold flex items-center space-x-2 shadow-glow hover:shadow-lg transition-all"
              >
                <span>Translate</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Right Output Card */}
          <div className="glass-card rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800/80 bg-white/40 dark:bg-[#0f1422]/60 flex flex-col h-[420px] justify-between shadow-xl relative overflow-hidden">
            
            {/* Loading Overlay */}
            <AnimatePresence>
              {loading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 bg-white/80 dark:bg-[#0f1422]/90 backdrop-blur-sm z-20 flex flex-col items-center justify-center space-y-4"
                >
                  <div className="relative w-12 h-12">
                    <span className="w-12 h-12 rounded-full border-4 border-slate-100 dark:border-slate-800 border-t-brand-500 dark:border-t-brand-400 inline-block animate-spin"></span>
                    <Sparkles className="w-5 h-5 text-brand-500 absolute top-3.5 left-3.5 animate-pulse" />
                  </div>
                  <div className="text-sm font-semibold text-slate-500 dark:text-slate-400 font-display">Analyzing Slang Vectors...</div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Content Area */}
            {translationResult ? (
              <div className="flex-1 flex flex-col justify-between h-full">
                
                {/* Result Top */}
                <div className="space-y-4">
                  <div className="flex items-center justify-between text-xs font-semibold text-slate-400 uppercase tracking-wider">
                    <span>Professional Translation</span>
                    <div className="flex items-center space-x-1 text-brand-500">
                      <Languages className="w-3.5 h-3.5" />
                      <span>{translationResult.language} Detected</span>
                    </div>
                  </div>
                  <p className="text-slate-900 dark:text-white text-lg font-semibold leading-relaxed min-h-[60px]">
                    {translationResult.translation}
                  </p>

                  {/* Metadata labels */}
                  <div className="grid grid-cols-3 gap-2.5 pt-2 text-xs">
                    <div className="p-2 rounded-xl bg-indigo-50/50 dark:bg-indigo-950/20 border border-indigo-100/40 dark:border-indigo-900/40">
                      <span className="block text-[10px] text-slate-400 font-semibold uppercase">Tone</span>
                      <span className="font-bold text-indigo-600 dark:text-indigo-400">{translationResult.tone}</span>
                    </div>
                    <div className="p-2 rounded-xl bg-purple-50/50 dark:bg-purple-950/20 border border-purple-100/40 dark:border-purple-900/40">
                      <span className="block text-[10px] text-slate-400 font-semibold uppercase">Intent</span>
                      <span className="font-bold text-purple-600 dark:text-purple-400">{translationResult.intent}</span>
                    </div>
                    <div className="p-2 rounded-xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100/40 dark:border-emerald-900/40">
                      <span className="block text-[10px] text-slate-400 font-semibold uppercase">Confidence</span>
                      <span className="font-bold text-emerald-600 dark:text-emerald-400">{(translationResult.confidence * 100).toFixed(0)}%</span>
                    </div>
                  </div>
                </div>

                {/* Suggested Replies */}
                <div className="space-y-2 mt-4">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Suggested Professional Replies (Click to Copy)</div>
                  <div className="space-y-1.5 max-h-[110px] overflow-y-auto pr-1">
                    {translationResult.replies.map((reply, i) => (
                      <button
                        key={i}
                        onClick={() => handleCopy(reply)}
                        className="w-full text-left p-2 border border-slate-100 dark:border-slate-800 rounded-xl bg-slate-50/50 dark:bg-slate-900/40 text-xs text-slate-600 dark:text-slate-300 hover:border-brand-500 hover:bg-brand-50/25 dark:hover:bg-brand-950/10 hover:text-brand-600 dark:hover:text-brand-400 transition-all truncate"
                      >
                        "{reply}"
                      </button>
                    ))}
                  </div>
                </div>

                {/* Result Bottom Action Controls */}
                <div className="flex items-center justify-between border-t border-slate-100 dark:border-slate-800/60 pt-4 mt-4">
                  <div className="flex space-x-2">
                    <button
                      onClick={() => handleCopy(translationResult.translation)}
                      className="p-2.5 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500 transition-colors"
                      title="Copy Translation"
                    >
                      {copied ? <Check className="w-4.5 h-4.5 text-green-500" /> : <Copy className="w-4.5 h-4.5" />}
                    </button>
                    <button
                      onClick={handleTextToSpeech}
                      className={`p-2.5 border rounded-xl transition-colors ${
                        speechActive 
                          ? 'border-brand-500 bg-brand-50/20 text-brand-500' 
                          : 'border-slate-200 dark:border-slate-800 text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500'
                      }`}
                      title="Speak Translation"
                    >
                      <Volume2 className="w-4.5 h-4.5" />
                    </button>
                    <button
                      onClick={handleShare}
                      className="p-2.5 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500 transition-colors"
                      title="Share link"
                    >
                      {shared ? <Check className="w-4.5 h-4.5 text-green-500" /> : <Share2 className="w-4.5 h-4.5" />}
                    </button>
                  </div>

                  {/* Downloads */}
                  <div className="flex space-x-2">
                    <button
                      onClick={() => handleDownloadFile('csv')}
                      className="px-3 py-2 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500 transition-colors text-xs font-semibold flex items-center space-x-1"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>CSV</span>
                    </button>
                    <button
                      onClick={() => handleDownloadFile('pdf')}
                      className="px-3 py-2 border border-slate-200 dark:border-slate-800 rounded-xl text-slate-500 dark:text-slate-400 hover:text-brand-500 hover:border-brand-500 transition-colors text-xs font-semibold flex items-center space-x-1"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>PDF</span>
                    </button>
                  </div>
                </div>

              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-slate-400 text-center space-y-4">
                <div className="w-16 h-16 rounded-2xl bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 flex items-center justify-center">
                  <Languages className="w-8 h-8 text-slate-300 dark:text-slate-700" />
                </div>
                <div>
                  <h3 className="font-semibold text-slate-700 dark:text-slate-300 text-sm sm:text-base">Awaiting Slang Input</h3>
                  <p className="text-xs max-w-[280px] mx-auto text-slate-400 mt-1">
                    Once you type slang in the left panel and click 'Translate', the formal translation will display here.
                  </p>
                </div>
              </div>
            )}
          </div>

        </div>

        {/* Demo instructions alert */}
        <div className="glass-card rounded-2xl p-4.5 border border-brand-200/50 bg-brand-50/20 dark:border-brand-950/20 dark:bg-brand-950/5 text-slate-500 dark:text-slate-400 text-xs sm:text-sm flex items-start space-x-2">
          <Sparkles className="w-5 h-5 text-brand-500 shrink-0 mt-0.5" />
          <span>
            <strong>Demo Tip:</strong> To see exact translation mappings, try pressing the 🎤 microphone button for a simulated voice input of popular slang. We also automatically index translations to user history databases if you are signed in!
          </span>
        </div>

      </div>
    </div>
  );
};
